#https://blog.min.io/setting-up-a-development-machine-with-mlflow-and-minio/
services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    environment:
      - AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_ACCESS_KEY}
      - MLFLOW_S3_ENDPOINT_URL=http://s3:${MINIO_PORT}
      - MLFLOW_S3_IGNORE_TLS=true
    depends_on:
      - s3
    ports:
      - "5000:5000"
    command: "mlflow server --host 0.0.0.0 --port 5000 --serve-artifacts --default-artifact-root s3://${MLFLOW_BUCKET_NAME}"

  s3:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9001" ]
      interval: 30s
      timeout: 20s
      retries: 3
