services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:  
      - "5000:5000"
    restart: always
    command: "mlflow server --host 0.0.0.0 --port 5000 --serve-artifacts"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
